---
# This workflow integrates qwiet.ai preZero with GitHub
# Visit https://docs.shiftleft.io for help
name: qwiet.ai

on:
  pull_request:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 11 * * 6'

jobs:
  NextGen-Static-AnalysisPostBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java JDK v8
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v4
      #with:
          #node-version-file: .node-version
          #cache: npm

    - name: Install Dependencies
      id: npm-ci
      run: npm ci

    - name: Lint
      id: npm-lint
      run: npm run lint

    - name: Test
      id: npm-ci-test
      run: npm run ci-test

    - name: Download ShiftLeft CLI
      run: |
         curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

    - name: preZero Static Analysis
      run: |
         ${GITHUB_WORKSPACE}/sl --version
         QWIET_EXTERNAL_SECRETS=true ${GITHUB_WORKSPACE}/sl analyze --strict --wait \
          --app QwietAI-javascript-GH \
          --tag branch=${{ github.head_ref }} \
          --container 18fgsa/s3-resource .
      env:
         SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
         SHIFTLEFT_API_HOST: www.shiftleft.io
         SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
         SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443
